"""
Django settings for hibh project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'hibh_api',
    'corsheaders'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hibh.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hibh.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRESQL_DB_NAME'),
        'USER': config('POSTGRESQL_DB_USER'),
        'PASSWORD': config('POSTGRESQL_DB_PASSWORD'),
        'HOST': config('POSTGRESQL_DB_HOST'),
        'PORT': config('POSTGRESQL_DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# email config

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = config("SMTP_HOSTNAME")
EMAIL_PORT = config("SMTP_PORT")
EMAIL_USE_TLS = False  # TLS security
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config("SMTP_USERNAME")
EMAIL_HOST_PASSWORD = config("SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_EMAIL")

FRONTEND_URL=config("FRONTEND_URL")
BACKEND_URL=config("BACKEND_URL")

IPGEOLOCATION_API_KEY = config("IPGEOLOCATION_API_KEY")

VERIFICATION_EMAIL_TEMPLATE = """
<h3>Verify Email to Enable Receiving ALerts</h3>
<p>
    The Tracker named "{{ name }}" is created using your email address. If it was you please verify the email by clicking below button. If it was not you please ignore this email.
    <br><br>
    To Verify Email, <a href="{{ backend_url }}/api/tracker/verify/{{ email_token }}">Click here</a>.
</p>
"""

ALERT_EMAIL_TEMPLATE = """
<h3>Unauthorized Access Alert</h3>
<p>
    The Tracker named "{{ tracker.name }}" that you have created has been triggered. Someone attempted to open your Personal Files. If it was not you, please take the necessary steps to block this unauthorized access.
    <br><br>
    IP Address: {{ alert.ip_address }}
    <br>
    User Agent: {{ alert.useragent }}
    <br>
    Location: {{ alert.country }}
    <br>
    Time: {{ alert.created_at|date:"DATETIME_FORMAT" }} UTC
    <br><br>
    To view complete details, <a href="{{ frontend_url }}/tracker/{{ tracker.private_key }}">click here</a>.
</p>
"""


# Allow all origins for simplicity. Customize as needed for your specific requirements.
CORS_ALLOW_ALL_ORIGINS = True

# Optional: Customize allowed headers, methods, and other CORS settings
# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "https://subdomain.example.com",
# ]

APPEND_SLASH=True