# Generated by Django 4.2.3 on 2023-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hibh_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="private_key",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="public_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
