# Generated by Django 4.2.3 on 2023-07-27 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "hibh_api",
            "0002_tracker_is_email_verified_alter_tracker_private_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tracker",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
