# Generated by Django 4.2.3 on 2023-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hibh_api", "0006_remove_tracker_email_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="email_token",
            field=models.CharField(default="aaaa", max_length=255),
            preserve_default=False,
        ),
    ]
